version: 1
disable_existing_loggers: False

formatters:
  uvicorn:
    format: '%(asctime)s - %(levelname)s - %(name)s - %(message)s [%(otelTraceID)s:%(otelSpanID)s]'

handlers:
  console:
    class: logging.StreamHandler
    formatter: uvicorn
    stream: ext://sys.stdout

loggers:
  uvicorn:
    handlers: [console]
    level: INFO
  uvicorn.error:
    handlers: [console]
    level: ERROR
    propagate: True
  uvicorn.access:
    handlers: [console]
    level: INFO
    propagate: False

root:
  handlers: [console]
  level: INFO
