apiVersion: apps/v1
kind: Deployment
metadata:
  name: app2
  namespace: fastapi-kafka
spec:
  replicas: 1
  selector:
    matchLabels:
      app: app2
  template:
    metadata:
      annotations:
        instrumentation.opentelemetry.io/inject-python: "true"
      labels:
        app: app2
    spec:
      containers:
        - name: app2
          image: app2:latest
          imagePullPolicy: Never
          ports:
            - containerPort: 8001
          env:
            - name: KAFKA_BOOTSTRAP_SERVERS
              value: kafka:9092
          livenessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 15
            periodSeconds: 20
          readinessProbe:
            httpGet:
              path: /health
              port: 8001
            initialDelaySeconds: 5
            periodSeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: app2
  namespace: fastapi-kafka
spec:
  selector:
    app: app2
  ports:
    - protocol: TCP
      port: 8001
      targetPort: 8001
